name: Deploy Node application

on:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@4
      - name: Create .env file
        run : |
               echo "MONGO_CONNECT_STRING=${{ secrets.MONGO_CONNECT_STRING}}" > .env
               echo "JWT_SECRET=${{ secrets.JWT_SECRET}}" >> .env

      - name: Login to Docker Hub
        run : docker login -u ${{ secrets.DOCKER_USER}} -p ${{ secrets.DOCKER_PASSWORD}}
      - name: Build Docker image
        run : docker build -t vinaybabu3962/work-order-management-api-service .
      - name: Publish image to docker hub
        run : docker push vinaybabu3962/work-order-management-api-service:latest
    
    deploy:
      needs: build
      runs-on: self-hosted
      steps:
        -name: Pull Image from docker hub
         run : docker pull vinaybabu3962/work-order-management-api-service:latest
        -name: Delete old container if exists
         run : docker rm -f nodejs-app-container
        -name: Run docker container 
         run : docker run -d -p 3000:3000 -name nodejs-app-container vinaybabu3962/work-order-management-api-service

